//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl, Version=1.1.4322.2032 自动生成。
// 
namespace WS 
{
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System;
	using System.Web.Services.Protocols;
	using System.ComponentModel;
	using System.Web.Services;
    
    
	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="egwsSoap", Namespace="http://tempuri.org/")]
	public class egws : System.Web.Services.Protocols.SoapHttpClientProtocol 
	{
        
		public egws() 
		{
			this.Url = "http://localhost/WS/egws.asmx";
		}

		/// <remarks/>
		public egws(string p_strUrl) 
		{
            try
            {
                this.Url = p_strUrl;
            }
            catch (Exception e)
            {
                System.Windows.Forms.MessageBox.Show(e.Message);
            }
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getEgSoap", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string getEgSoap(string p_str) 
		{
            try
            {
                object[] results = this.Invoke("getEgSoap", new object[] {
																		 p_str});
                return ((string)(results[0]));
            }
            catch (Exception ee)
            {
                //try
                //{
                //    object[] results = this.Invoke("getEgSoap", new object[] {
                //                                                         p_str});
                //    return ((string)(results[0]));
                //}
                //catch(Exception ee)
                //{
                //    System.Windows.Forms.MessageBox.Show(ee.Message);
                //}

            }
            return "";
		}
        
		/// <remarks/>
		public System.IAsyncResult BegingetEgSoap(string p_str, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("getEgSoap", new object[] {p_str}, callback, asyncState);
		}
        
		/// <remarks/>
		public string EndgetEgSoap(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}
	}
}
