//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.1。
// 
namespace EagleWebService
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "WebServiceSoap", Namespace = "http://tempuri.org/")]
    public partial class wsInsurrance : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;

        private System.Threading.SendOrPostCallback LoginOperationCompleted;

        private System.Threading.SendOrPostCallback LogoutOperationCompleted;

        private System.Threading.SendOrPostCallback GetPolicyOperationCompleted;

        private System.Threading.SendOrPostCallback GetPolicyListOperationCompleted;

        private System.Threading.SendOrPostCallback GetPolicyListBetweenOperationCompleted;

        private System.Threading.SendOrPostCallback DiscardItOperationCompleted;

        private System.Threading.SendOrPostCallback CountBalanceOperationCompleted;

        private System.Threading.SendOrPostCallback CountConsumedOperationCompleted;

        private System.Threading.SendOrPostCallback PurchaseOperationCompleted;

        private System.Threading.SendOrPostCallback FeedbackOperationCompleted;

        private System.Threading.SendOrPostCallback GetProductListOperationCompleted;

        /// <remarks/>
        public wsInsurrance()
        {
            switch (Options.GlobalVar.SelectedISP)
            {
                case XMLConfig.ISP.ChinaTelecom:
                    this.Url = Options.GlobalVar.IAWebServiceURL1;
                    break;
                case XMLConfig.ISP.ChinaUnicom:
                    this.Url = Options.GlobalVar.IAWebServiceURL2;
                    break;
                default:
                    this.Url = Options.GlobalVar.IAWebServiceURL;
                    break;
            }
        }

        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;

        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;

        /// <remarks/>
        public event LogoutCompletedEventHandler LogoutCompleted;

        /// <remarks/>
        public event GetPolicyCompletedEventHandler GetPolicyCompleted;

        /// <remarks/>
        public event GetPolicyListCompletedEventHandler GetPolicyListCompleted;

        /// <remarks/>
        public event GetPolicyListBetweenCompletedEventHandler GetPolicyListBetweenCompleted;

        /// <remarks/>
        public event DiscardItCompletedEventHandler DiscardItCompleted;

        /// <remarks/>
        public event CountBalanceCompletedEventHandler CountBalanceCompleted;

        /// <remarks/>
        public event CountConsumedCompletedEventHandler CountConsumedCompleted;

        /// <remarks/>
        public event PurchaseCompletedEventHandler PurchaseCompleted;

        /// <remarks/>
        public event FeedbackCompletedEventHandler FeedbackCompleted;

        /// <remarks/>
        public event GetProductListCompletedEventHandler GetProductListCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld(string test)
        {
            object[] results = this.Invoke("HelloWorld", new object[] {
                        test});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(string test, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("HelloWorld", new object[] {
                        test}, callback, asyncState);
        }

        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void HelloWorldAsync(string test)
        {
            this.HelloWorldAsync(test, null);
        }

        /// <remarks/>
        public void HelloWorldAsync(string test, object userState)
        {
            if ((this.HelloWorldOperationCompleted == null))
            {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[] {
                        test}, this.HelloWorldOperationCompleted, userState);
        }

        private void OnHelloWorldOperationCompleted(object arg)
        {
            if ((this.HelloWorldCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserLoginResponse Login(string username, string password)
        {
            object[] results = this.Invoke("Login", new object[] {
                        username,
                        password});
            return ((UserLoginResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginLogin(string username, string password, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Login", new object[] {
                        username,
                        password}, callback, asyncState);
        }

        /// <remarks/>
        public UserLoginResponse EndLogin(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((UserLoginResponse)(results[0]));
        }

        /// <remarks/>
        public void LoginAsync(string username, string password)
        {
            this.LoginAsync(username, password, null);
        }

        /// <remarks/>
        public void LoginAsync(string username, string password, object userState)
        {
            if ((this.LoginOperationCompleted == null))
            {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        username,
                        password}, this.LoginOperationCompleted, userState);
        }

        private void OnLoginOperationCompleted(object arg)
        {
            if ((this.LoginCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Logout", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TraceEntity Logout(LogoutRequestEntity request)
        {
            object[] results = this.Invoke("Logout", new object[] {
                        request});
            return ((TraceEntity)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginLogout(LogoutRequestEntity request, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Logout", new object[] {
                        request}, callback, asyncState);
        }

        /// <remarks/>
        public TraceEntity EndLogout(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((TraceEntity)(results[0]));
        }

        /// <remarks/>
        public void LogoutAsync(LogoutRequestEntity request)
        {
            this.LogoutAsync(request, null);
        }

        /// <remarks/>
        public void LogoutAsync(LogoutRequestEntity request, object userState)
        {
            if ((this.LogoutOperationCompleted == null))
            {
                this.LogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutOperationCompleted);
            }
            this.InvokeAsync("Logout", new object[] {
                        request}, this.LogoutOperationCompleted, userState);
        }

        private void OnLogoutOperationCompleted(object arg)
        {
            if ((this.LogoutCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogoutCompleted(this, new LogoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPolicy", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PolicyResponseEntity GetPolicy(string username, string password, string caseNo)
        {
            object[] results = this.Invoke("GetPolicy", new object[] {
                        username,
                        password,
                        caseNo});
            return ((PolicyResponseEntity)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetPolicy(string username, string password, string caseNo, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetPolicy", new object[] {
                        username,
                        password,
                        caseNo}, callback, asyncState);
        }

        /// <remarks/>
        public PolicyResponseEntity EndGetPolicy(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((PolicyResponseEntity)(results[0]));
        }

        /// <remarks/>
        public void GetPolicyAsync(string username, string password, string caseNo)
        {
            this.GetPolicyAsync(username, password, caseNo, null);
        }

        /// <remarks/>
        public void GetPolicyAsync(string username, string password, string caseNo, object userState)
        {
            if ((this.GetPolicyOperationCompleted == null))
            {
                this.GetPolicyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPolicyOperationCompleted);
            }
            this.InvokeAsync("GetPolicy", new object[] {
                        username,
                        password,
                        caseNo}, this.GetPolicyOperationCompleted, userState);
        }

        private void OnGetPolicyOperationCompleted(object arg)
        {
            if ((this.GetPolicyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPolicyCompleted(this, new GetPolicyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPolicyList", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PolicyListResponseEntity GetPolicyList(string username, string password, int pageSize)
        {
            object[] results = this.Invoke("GetPolicyList", new object[] {
                        username,
                        password,
                        pageSize});
            return ((PolicyListResponseEntity)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetPolicyList(string username, string password, int pageSize, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetPolicyList", new object[] {
                        username,
                        password,
                        pageSize}, callback, asyncState);
        }

        /// <remarks/>
        public PolicyListResponseEntity EndGetPolicyList(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((PolicyListResponseEntity)(results[0]));
        }

        /// <remarks/>
        public void GetPolicyListAsync(string username, string password, int pageSize)
        {
            this.GetPolicyListAsync(username, password, pageSize, null);
        }

        /// <remarks/>
        public void GetPolicyListAsync(string username, string password, int pageSize, object userState)
        {
            if ((this.GetPolicyListOperationCompleted == null))
            {
                this.GetPolicyListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPolicyListOperationCompleted);
            }
            this.InvokeAsync("GetPolicyList", new object[] {
                        username,
                        password,
                        pageSize}, this.GetPolicyListOperationCompleted, userState);
        }

        private void OnGetPolicyListOperationCompleted(object arg)
        {
            if ((this.GetPolicyListCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPolicyListCompleted(this, new GetPolicyListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPolicyListBetween", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PolicyListResponseEntity GetPolicyListBetween(string username, string password, System.DateTime dtStart, System.DateTime dtEnd)
        {
            object[] results = this.Invoke("GetPolicyListBetween", new object[] {
                        username,
                        password,
                        dtStart,
                        dtEnd});
            return ((PolicyListResponseEntity)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetPolicyListBetween(string username, string password, System.DateTime dtStart, System.DateTime dtEnd, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetPolicyListBetween", new object[] {
                        username,
                        password,
                        dtStart,
                        dtEnd}, callback, asyncState);
        }

        /// <remarks/>
        public PolicyListResponseEntity EndGetPolicyListBetween(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((PolicyListResponseEntity)(results[0]));
        }

        /// <remarks/>
        public void GetPolicyListBetweenAsync(string username, string password, System.DateTime dtStart, System.DateTime dtEnd)
        {
            this.GetPolicyListBetweenAsync(username, password, dtStart, dtEnd, null);
        }

        /// <remarks/>
        public void GetPolicyListBetweenAsync(string username, string password, System.DateTime dtStart, System.DateTime dtEnd, object userState)
        {
            if ((this.GetPolicyListBetweenOperationCompleted == null))
            {
                this.GetPolicyListBetweenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPolicyListBetweenOperationCompleted);
            }
            this.InvokeAsync("GetPolicyListBetween", new object[] {
                        username,
                        password,
                        dtStart,
                        dtEnd}, this.GetPolicyListBetweenOperationCompleted, userState);
        }

        private void OnGetPolicyListBetweenOperationCompleted(object arg)
        {
            if ((this.GetPolicyListBetweenCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPolicyListBetweenCompleted(this, new GetPolicyListBetweenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DiscardIt", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TraceEntity DiscardIt(string username, string password, string caseNo)
        {
            object[] results = this.Invoke("DiscardIt", new object[] {
                        username,
                        password,
                        caseNo});
            return ((TraceEntity)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDiscardIt(string username, string password, string caseNo, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DiscardIt", new object[] {
                        username,
                        password,
                        caseNo}, callback, asyncState);
        }

        /// <remarks/>
        public TraceEntity EndDiscardIt(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((TraceEntity)(results[0]));
        }

        /// <remarks/>
        public void DiscardItAsync(string username, string password, string caseNo)
        {
            this.DiscardItAsync(username, password, caseNo, null);
        }

        /// <remarks/>
        public void DiscardItAsync(string username, string password, string caseNo, object userState)
        {
            if ((this.DiscardItOperationCompleted == null))
            {
                this.DiscardItOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDiscardItOperationCompleted);
            }
            this.InvokeAsync("DiscardIt", new object[] {
                        username,
                        password,
                        caseNo}, this.DiscardItOperationCompleted, userState);
        }

        private void OnDiscardItOperationCompleted(object arg)
        {
            if ((this.DiscardItCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DiscardItCompleted(this, new DiscardItCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CountBalance", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CountBalance(string username, string password)
        {
            object[] results = this.Invoke("CountBalance", new object[] {
                        username,
                        password});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCountBalance(string username, string password, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CountBalance", new object[] {
                        username,
                        password}, callback, asyncState);
        }

        /// <remarks/>
        public int EndCountBalance(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        public void CountBalanceAsync(string username, string password)
        {
            this.CountBalanceAsync(username, password, null);
        }

        /// <remarks/>
        public void CountBalanceAsync(string username, string password, object userState)
        {
            if ((this.CountBalanceOperationCompleted == null))
            {
                this.CountBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCountBalanceOperationCompleted);
            }
            this.InvokeAsync("CountBalance", new object[] {
                        username,
                        password}, this.CountBalanceOperationCompleted, userState);
        }

        private void OnCountBalanceOperationCompleted(object arg)
        {
            if ((this.CountBalanceCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CountBalanceCompleted(this, new CountBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CountConsumed", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CountConsumed(string username, string password)
        {
            object[] results = this.Invoke("CountConsumed", new object[] {
                        username,
                        password});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCountConsumed(string username, string password, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CountConsumed", new object[] {
                        username,
                        password}, callback, asyncState);
        }

        /// <remarks/>
        public int EndCountConsumed(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        public void CountConsumedAsync(string username, string password)
        {
            this.CountConsumedAsync(username, password, null);
        }

        /// <remarks/>
        public void CountConsumedAsync(string username, string password, object userState)
        {
            if ((this.CountConsumedOperationCompleted == null))
            {
                this.CountConsumedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCountConsumedOperationCompleted);
            }
            this.InvokeAsync("CountConsumed", new object[] {
                        username,
                        password}, this.CountConsumedOperationCompleted, userState);
        }

        private void OnCountConsumedOperationCompleted(object arg)
        {
            if ((this.CountConsumedCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CountConsumedCompleted(this, new CountConsumedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Purchase", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PurchaseResponseEntity Purchase(PurchaseRequestEntity request)
        {
            object[] results = this.Invoke("Purchase", new object[] {
                        request});
            return ((PurchaseResponseEntity)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginPurchase(PurchaseRequestEntity request, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Purchase", new object[] {
                        request}, callback, asyncState);
        }

        /// <remarks/>
        public PurchaseResponseEntity EndPurchase(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((PurchaseResponseEntity)(results[0]));
        }

        /// <remarks/>
        public void PurchaseAsync(PurchaseRequestEntity request)
        {
            this.PurchaseAsync(request, null);
        }

        /// <remarks/>
        public void PurchaseAsync(PurchaseRequestEntity request, object userState)
        {
            if ((this.PurchaseOperationCompleted == null))
            {
                this.PurchaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPurchaseOperationCompleted);
            }
            this.InvokeAsync("Purchase", new object[] {
                        request}, this.PurchaseOperationCompleted, userState);
        }

        private void OnPurchaseOperationCompleted(object arg)
        {
            if ((this.PurchaseCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PurchaseCompleted(this, new PurchaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Feedback", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TraceEntity Feedback(t_Feedback request)
        {
            object[] results = this.Invoke("Feedback", new object[] {
                        request});
            return ((TraceEntity)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginFeedback(t_Feedback request, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Feedback", new object[] {
                        request}, callback, asyncState);
        }

        /// <remarks/>
        public TraceEntity EndFeedback(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((TraceEntity)(results[0]));
        }

        /// <remarks/>
        public void FeedbackAsync(t_Feedback request)
        {
            this.FeedbackAsync(request, null);
        }

        /// <remarks/>
        public void FeedbackAsync(t_Feedback request, object userState)
        {
            if ((this.FeedbackOperationCompleted == null))
            {
                this.FeedbackOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFeedbackOperationCompleted);
            }
            this.InvokeAsync("Feedback", new object[] {
                        request}, this.FeedbackOperationCompleted, userState);
        }

        private void OnFeedbackOperationCompleted(object arg)
        {
            if ((this.FeedbackCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FeedbackCompleted(this, new FeedbackCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductList", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductListResponseEntity GetProductList(string username, string password)
        {
            object[] results = this.Invoke("GetProductList", new object[] {
                        username,
                        password});
            return ((ProductListResponseEntity)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetProductList(string username, string password, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetProductList", new object[] {
                        username,
                        password}, callback, asyncState);
        }

        /// <remarks/>
        public ProductListResponseEntity EndGetProductList(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ProductListResponseEntity)(results[0]));
        }

        /// <remarks/>
        public void GetProductListAsync(string username, string password)
        {
            this.GetProductListAsync(username, password, null);
        }

        /// <remarks/>
        public void GetProductListAsync(string username, string password, object userState)
        {
            if ((this.GetProductListOperationCompleted == null))
            {
                this.GetProductListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductListOperationCompleted);
            }
            this.InvokeAsync("GetProductList", new object[] {
                        username,
                        password}, this.GetProductListOperationCompleted, userState);
        }

        private void OnGetProductListOperationCompleted(object arg)
        {
            if ((this.GetProductListCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductListCompleted(this, new GetProductListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class UserLoginResponse
    {

        private string usernameField;

        private int userIdField;

        private UserType typeField;

        private string displayNameField;

        private int offsetXField;

        private int offsetYField;

        private string parentPathField;

        private decimal balanceField;

        private int countWithdrawedField;

        private int countConsumedField;

        private TraceEntity traceField;

        /// <remarks/>
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        public int UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public UserType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string DisplayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }

        /// <remarks/>
        public int OffsetX
        {
            get
            {
                return this.offsetXField;
            }
            set
            {
                this.offsetXField = value;
            }
        }

        /// <remarks/>
        public int OffsetY
        {
            get
            {
                return this.offsetYField;
            }
            set
            {
                this.offsetYField = value;
            }
        }

        /// <remarks/>
        public string ParentPath
        {
            get
            {
                return this.parentPathField;
            }
            set
            {
                this.parentPathField = value;
            }
        }

        /// <remarks/>
        public decimal Balance
        {
            get
            {
                return this.balanceField;
            }
            set
            {
                this.balanceField = value;
            }
        }

        /// <remarks/>
        public int CountWithdrawed
        {
            get
            {
                return this.countWithdrawedField;
            }
            set
            {
                this.countWithdrawedField = value;
            }
        }

        /// <remarks/>
        public int CountConsumed
        {
            get
            {
                return this.countConsumedField;
            }
            set
            {
                this.countConsumedField = value;
            }
        }

        /// <remarks/>
        public TraceEntity Trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public enum UserType
    {

        /// <remarks/>
        AdminPlus,

        /// <remarks/>
        Admin,

        /// <remarks/>
        Default,

        /// <remarks/>
        Insurer,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class TraceEntity
    {

        private string errorMsgField;

        private string detailField;

        /// <remarks/>
        public string ErrorMsg
        {
            get
            {
                return this.errorMsgField;
            }
            set
            {
                this.errorMsgField = value;
            }
        }

        /// <remarks/>
        public string Detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class t_Product
    {

        private int productIDField;

        private string productNameField;

        private string productSupplierField;

        private int productDurationField;

        private string productCommentField;

        private string printingConfigField;

        private string filterIncludeField;

        private string filterExcludeField;

        private string filterCommentField;

        private System.Nullable<System.DateTime> timespanField;

        private bool enabledField;

        private bool isIssuingRequiredField;

        private string iOC_Class_AliasField;

        /// <remarks/>
        public int productID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }

        /// <remarks/>
        public string productName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }

        /// <remarks/>
        public string productSupplier
        {
            get
            {
                return this.productSupplierField;
            }
            set
            {
                this.productSupplierField = value;
            }
        }

        /// <remarks/>
        public int productDuration
        {
            get
            {
                return this.productDurationField;
            }
            set
            {
                this.productDurationField = value;
            }
        }

        /// <remarks/>
        public string productComment
        {
            get
            {
                return this.productCommentField;
            }
            set
            {
                this.productCommentField = value;
            }
        }

        /// <remarks/>
        public string PrintingConfig
        {
            get
            {
                return this.printingConfigField;
            }
            set
            {
                this.printingConfigField = value;
            }
        }

        /// <remarks/>
        public string FilterInclude
        {
            get
            {
                return this.filterIncludeField;
            }
            set
            {
                this.filterIncludeField = value;
            }
        }

        /// <remarks/>
        public string FilterExclude
        {
            get
            {
                return this.filterExcludeField;
            }
            set
            {
                this.filterExcludeField = value;
            }
        }

        /// <remarks/>
        public string FilterComment
        {
            get
            {
                return this.filterCommentField;
            }
            set
            {
                this.filterCommentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> Timespan
        {
            get
            {
                return this.timespanField;
            }
            set
            {
                this.timespanField = value;
            }
        }

        /// <remarks/>
        public bool Enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }

        /// <remarks/>
        public bool IsIssuingRequired
        {
            get
            {
                return this.isIssuingRequiredField;
            }
            set
            {
                this.isIssuingRequiredField = value;
            }
        }

        /// <remarks/>
        public string IOC_Class_Alias
        {
            get
            {
                return this.iOC_Class_AliasField;
            }
            set
            {
                this.iOC_Class_AliasField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class ProductListResponseEntity
    {

        private t_Product[] productListField;

        private TraceEntity traceField;

        /// <remarks/>
        public t_Product[] ProductList
        {
            get
            {
                return this.productListField;
            }
            set
            {
                this.productListField = value;
            }
        }

        /// <remarks/>
        public TraceEntity Trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class t_Feedback
    {

        private long idField;

        private string subjectField;

        private string fromWhoField;

        private string fromLocationField;

        private string fromIPField;

        private string remarkField;

        private System.Nullable<int> timerField;

        private System.DateTime timespanField;

        /// <remarks/>
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }

        /// <remarks/>
        public string fromWho
        {
            get
            {
                return this.fromWhoField;
            }
            set
            {
                this.fromWhoField = value;
            }
        }

        /// <remarks/>
        public string fromLocation
        {
            get
            {
                return this.fromLocationField;
            }
            set
            {
                this.fromLocationField = value;
            }
        }

        /// <remarks/>
        public string fromIP
        {
            get
            {
                return this.fromIPField;
            }
            set
            {
                this.fromIPField = value;
            }
        }

        /// <remarks/>
        public string remark
        {
            get
            {
                return this.remarkField;
            }
            set
            {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> timer
        {
            get
            {
                return this.timerField;
            }
            set
            {
                this.timerField = value;
            }
        }

        /// <remarks/>
        public System.DateTime timespan
        {
            get
            {
                return this.timespanField;
            }
            set
            {
                this.timespanField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class PurchaseResponseEntity
    {

        private string policyNoField;

        private string caseNoField;

        private string serialNoField;

        private string agentNameField;

        private string insurerField;

        private string amountInsuredField;

        private string validationPhoneNumberField;

        private string validationWebsiteField;

        private TraceEntity traceField;

        /// <remarks/>
        public string PolicyNo
        {
            get
            {
                return this.policyNoField;
            }
            set
            {
                this.policyNoField = value;
            }
        }

        /// <remarks/>
        public string CaseNo
        {
            get
            {
                return this.caseNoField;
            }
            set
            {
                this.caseNoField = value;
            }
        }

        /// <remarks/>
        public string SerialNo
        {
            get
            {
                return this.serialNoField;
            }
            set
            {
                this.serialNoField = value;
            }
        }

        /// <remarks/>
        public string AgentName
        {
            get
            {
                return this.agentNameField;
            }
            set
            {
                this.agentNameField = value;
            }
        }

        /// <remarks/>
        public string Insurer
        {
            get
            {
                return this.insurerField;
            }
            set
            {
                this.insurerField = value;
            }
        }

        /// <remarks/>
        public string AmountInsured
        {
            get
            {
                return this.amountInsuredField;
            }
            set
            {
                this.amountInsuredField = value;
            }
        }

        /// <remarks/>
        public string ValidationPhoneNumber
        {
            get
            {
                return this.validationPhoneNumberField;
            }
            set
            {
                this.validationPhoneNumberField = value;
            }
        }

        /// <remarks/>
        public string ValidationWebsite
        {
            get
            {
                return this.validationWebsiteField;
            }
            set
            {
                this.validationWebsiteField = value;
            }
        }

        /// <remarks/>
        public TraceEntity Trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class PurchaseRequestEntity
    {

        private string insuranceCodeField;

        private string usernameField;

        private string passwordField;

        private System.DateTime flightDateField;

        private string flightNoField;

        private Gender customerGenderField;

        private System.DateTime customerBirthField;

        private IdentityType customerIDTypeField;

        private string customerIDField;

        private string customerNameField;

        private string customerPhoneField;

        private string pNRField;

        private string reservedField;

        /// <remarks/>
        public string InsuranceCode
        {
            get
            {
                return this.insuranceCodeField;
            }
            set
            {
                this.insuranceCodeField = value;
            }
        }

        /// <remarks/>
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public System.DateTime flightDate
        {
            get
            {
                return this.flightDateField;
            }
            set
            {
                this.flightDateField = value;
            }
        }

        /// <remarks/>
        public string flightNo
        {
            get
            {
                return this.flightNoField;
            }
            set
            {
                this.flightNoField = value;
            }
        }

        /// <remarks/>
        public Gender customerGender
        {
            get
            {
                return this.customerGenderField;
            }
            set
            {
                this.customerGenderField = value;
            }
        }

        /// <remarks/>
        public System.DateTime customerBirth
        {
            get
            {
                return this.customerBirthField;
            }
            set
            {
                this.customerBirthField = value;
            }
        }

        /// <remarks/>
        public IdentityType customerIDType
        {
            get
            {
                return this.customerIDTypeField;
            }
            set
            {
                this.customerIDTypeField = value;
            }
        }

        /// <remarks/>
        public string customerID
        {
            get
            {
                return this.customerIDField;
            }
            set
            {
                this.customerIDField = value;
            }
        }

        /// <remarks/>
        public string customerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }

        /// <remarks/>
        public string customerPhone
        {
            get
            {
                return this.customerPhoneField;
            }
            set
            {
                this.customerPhoneField = value;
            }
        }

        /// <remarks/>
        public string PNR
        {
            get
            {
                return this.pNRField;
            }
            set
            {
                this.pNRField = value;
            }
        }

        /// <remarks/>
        public string Reserved
        {
            get
            {
                return this.reservedField;
            }
            set
            {
                this.reservedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public enum Gender
    {

        /// <remarks/>
        Female,

        /// <remarks/>
        Male,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public enum IdentityType
    {

        /// <remarks/>
        身份证,

        /// <remarks/>
        护照,

        /// <remarks/>
        军官证,

        /// <remarks/>
        士兵证,

        /// <remarks/>
        港澳通行证,

        /// <remarks/>
        其他证件,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class Policy
    {

        private string caseNoField;

        private string customerNameField;

        private string customerIDField;

        private string customerFlightNoField;

        private System.DateTime customerFlightDateField;

        private System.DateTime datetimeField;

        private bool enabledField;

        private string certNoField;

        private string productNameField;

        /// <remarks/>
        public string caseNo
        {
            get
            {
                return this.caseNoField;
            }
            set
            {
                this.caseNoField = value;
            }
        }

        /// <remarks/>
        public string customerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }

        /// <remarks/>
        public string customerID
        {
            get
            {
                return this.customerIDField;
            }
            set
            {
                this.customerIDField = value;
            }
        }

        /// <remarks/>
        public string customerFlightNo
        {
            get
            {
                return this.customerFlightNoField;
            }
            set
            {
                this.customerFlightNoField = value;
            }
        }

        /// <remarks/>
        public System.DateTime customerFlightDate
        {
            get
            {
                return this.customerFlightDateField;
            }
            set
            {
                this.customerFlightDateField = value;
            }
        }

        /// <remarks/>
        public System.DateTime datetime
        {
            get
            {
                return this.datetimeField;
            }
            set
            {
                this.datetimeField = value;
            }
        }

        /// <remarks/>
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }

        /// <remarks/>
        public string CertNo
        {
            get
            {
                return this.certNoField;
            }
            set
            {
                this.certNoField = value;
            }
        }

        /// <remarks/>
        public string ProductName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class PolicyListResponseEntity
    {

        private Policy[] policyListField;

        private TraceEntity traceField;

        /// <remarks/>
        public Policy[] PolicyList
        {
            get
            {
                return this.policyListField;
            }
            set
            {
                this.policyListField = value;
            }
        }

        /// <remarks/>
        public TraceEntity Trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class t_Case
    {

        private string caseOwnerDisplayField;

        private int caseIDField;

        private string caseNoField;

        private string caseOwnerField;

        private string caseSupplierField;

        private int productIDField;

        private int caseDurationField;

        private string customerNameField;

        private string customerIDField;

        private string customerPhoneField;

        private string customerFlightNoField;

        private System.DateTime customerFlightDateField;

        private string beneficiaryField;

        private System.DateTime datetimeField;

        private bool isIssuedField;

        private bool isPrintedField;

        private bool isSMSentField;

        private bool isQueryedField;

        private System.Nullable<System.DateTime> queryedDatetimeField;

        private bool enabledField;

        private string ipField;

        private string ipLocationField;

        private string certNoField;

        private string reservedField;

        private string printingNoField;

        /// <remarks/>
        public string caseOwnerDisplay
        {
            get
            {
                return this.caseOwnerDisplayField;
            }
            set
            {
                this.caseOwnerDisplayField = value;
            }
        }

        /// <remarks/>
        public int caseID
        {
            get
            {
                return this.caseIDField;
            }
            set
            {
                this.caseIDField = value;
            }
        }

        /// <remarks/>
        public string caseNo
        {
            get
            {
                return this.caseNoField;
            }
            set
            {
                this.caseNoField = value;
            }
        }

        /// <remarks/>
        public string caseOwner
        {
            get
            {
                return this.caseOwnerField;
            }
            set
            {
                this.caseOwnerField = value;
            }
        }

        /// <remarks/>
        public string caseSupplier
        {
            get
            {
                return this.caseSupplierField;
            }
            set
            {
                this.caseSupplierField = value;
            }
        }

        /// <remarks/>
        public int productID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }

        /// <remarks/>
        public int caseDuration
        {
            get
            {
                return this.caseDurationField;
            }
            set
            {
                this.caseDurationField = value;
            }
        }

        /// <remarks/>
        public string customerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }

        /// <remarks/>
        public string customerID
        {
            get
            {
                return this.customerIDField;
            }
            set
            {
                this.customerIDField = value;
            }
        }

        /// <remarks/>
        public string customerPhone
        {
            get
            {
                return this.customerPhoneField;
            }
            set
            {
                this.customerPhoneField = value;
            }
        }

        /// <remarks/>
        public string customerFlightNo
        {
            get
            {
                return this.customerFlightNoField;
            }
            set
            {
                this.customerFlightNoField = value;
            }
        }

        /// <remarks/>
        public System.DateTime customerFlightDate
        {
            get
            {
                return this.customerFlightDateField;
            }
            set
            {
                this.customerFlightDateField = value;
            }
        }

        /// <remarks/>
        public string beneficiary
        {
            get
            {
                return this.beneficiaryField;
            }
            set
            {
                this.beneficiaryField = value;
            }
        }

        /// <remarks/>
        public System.DateTime datetime
        {
            get
            {
                return this.datetimeField;
            }
            set
            {
                this.datetimeField = value;
            }
        }

        /// <remarks/>
        public bool isIssued
        {
            get
            {
                return this.isIssuedField;
            }
            set
            {
                this.isIssuedField = value;
            }
        }

        /// <remarks/>
        public bool isPrinted
        {
            get
            {
                return this.isPrintedField;
            }
            set
            {
                this.isPrintedField = value;
            }
        }

        /// <remarks/>
        public bool isSMSent
        {
            get
            {
                return this.isSMSentField;
            }
            set
            {
                this.isSMSentField = value;
            }
        }

        /// <remarks/>
        public bool isQueryed
        {
            get
            {
                return this.isQueryedField;
            }
            set
            {
                this.isQueryedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> QueryedDatetime
        {
            get
            {
                return this.queryedDatetimeField;
            }
            set
            {
                this.queryedDatetimeField = value;
            }
        }

        /// <remarks/>
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }

        /// <remarks/>
        public string IP
        {
            get
            {
                return this.ipField;
            }
            set
            {
                this.ipField = value;
            }
        }

        /// <remarks/>
        public string IpLocation
        {
            get
            {
                return this.ipLocationField;
            }
            set
            {
                this.ipLocationField = value;
            }
        }

        /// <remarks/>
        public string CertNo
        {
            get
            {
                return this.certNoField;
            }
            set
            {
                this.certNoField = value;
            }
        }

        /// <remarks/>
        public string reserved
        {
            get
            {
                return this.reservedField;
            }
            set
            {
                this.reservedField = value;
            }
        }

        /// <remarks/>
        public string PrintingNo
        {
            get
            {
                return this.printingNoField;
            }
            set
            {
                this.printingNoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class PolicyResponseEntity
    {

        private t_Case policyField;

        private TraceEntity traceField;

        /// <remarks/>
        public t_Case Policy
        {
            get
            {
                return this.policyField;
            }
            set
            {
                this.policyField = value;
            }
        }

        /// <remarks/>
        public TraceEntity Trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class LogoutRequestEntity
    {

        private string usernameField;

        private string passwordField;

        private int offsetXField;

        private int offsetYField;

        /// <remarks/>
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public int OffsetX
        {
            get
            {
                return this.offsetXField;
            }
            set
            {
                this.offsetXField = value;
            }
        }

        /// <remarks/>
        public int OffsetY
        {
            get
            {
                return this.offsetYField;
            }
            set
            {
                this.offsetYField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public UserLoginResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((UserLoginResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void LogoutCompletedEventHandler(object sender, LogoutCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal LogoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public TraceEntity Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((TraceEntity)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetPolicyCompletedEventHandler(object sender, GetPolicyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPolicyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetPolicyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public PolicyResponseEntity Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((PolicyResponseEntity)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetPolicyListCompletedEventHandler(object sender, GetPolicyListCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPolicyListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetPolicyListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public PolicyListResponseEntity Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((PolicyListResponseEntity)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetPolicyListBetweenCompletedEventHandler(object sender, GetPolicyListBetweenCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPolicyListBetweenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetPolicyListBetweenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public PolicyListResponseEntity Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((PolicyListResponseEntity)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void DiscardItCompletedEventHandler(object sender, DiscardItCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DiscardItCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DiscardItCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public TraceEntity Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((TraceEntity)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void CountBalanceCompletedEventHandler(object sender, CountBalanceCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CountBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CountBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void CountConsumedCompletedEventHandler(object sender, CountConsumedCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CountConsumedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CountConsumedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void PurchaseCompletedEventHandler(object sender, PurchaseCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PurchaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal PurchaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public PurchaseResponseEntity Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((PurchaseResponseEntity)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void FeedbackCompletedEventHandler(object sender, FeedbackCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FeedbackCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal FeedbackCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public TraceEntity Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((TraceEntity)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetProductListCompletedEventHandler(object sender, GetProductListCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetProductListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ProductListResponseEntity Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ProductListResponseEntity)(this.results[0]));
            }
        }
    }
}
