//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2300
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl, Version=1.1.4322.2300 自动生成。
// 
namespace logic 
{
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System;
	using System.Web.Services.Protocols;
	using System.ComponentModel;
	using System.Web.Services;
    
    
	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="egwsSoap", Namespace="http://tempuri.org/")]
	public class clws : System.Web.Services.Protocols.SoapHttpClientProtocol 
	{
        
		/// <remarks/>
		public clws() 
		{
			this.Url = "http://localhost/WS/egws.asmx";
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getEgSoap", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string getEgSoap(string p_str) 
		{
			object[] results = this.Invoke("getEgSoap", new object[] {
																		 p_str});
			return ((string)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BegingetEgSoap(string p_str, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("getEgSoap", new object[] {
																  p_str}, callback, asyncState);
		}
        
		/// <remarks/>
		public string EndgetEgSoap(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAgentInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string getAgentInfo(string p_strAgentId) 
		{
			object[] results = this.Invoke("getAgentInfo", new object[] {
																			p_strAgentId});
			return ((string)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BegingetAgentInfo(string p_strAgentId, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("getAgentInfo", new object[] {
																	 p_strAgentId}, callback, asyncState);
		}
        
		/// <remarks/>
		public string EndgetAgentInfo(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSevInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string getSevInfo(string p_strPassPort) 
		{
			object[] results = this.Invoke("getSevInfo", new object[] {
																		  p_strPassPort});
			return ((string)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BegingetSevInfo(string p_strPassPort, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("getSevInfo", new object[] {
																   p_strPassPort}, callback, asyncState);
		}
        
		/// <remarks/>
		public string EndgetSevInfo(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}
	}
}
