//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace Options.wsIBE {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HiWSPortBinding", Namespace="http://hi.me.org/")]
    public partial class HiWSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sayHiOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsAVOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsFDOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsRTOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsXePnrOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsSSOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsRT2OperationCompleted;
        
        private System.Threading.SendOrPostCallback wsFD2OperationCompleted;
        
        private System.Threading.SendOrPostCallback wsDSGOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsGetServerTimeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HiWSService() {
            this.Url = global::Options.Properties.Settings.Default.Options_wsIBE_HiWSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sayHiCompletedEventHandler sayHiCompleted;
        
        /// <remarks/>
        public event wsAVCompletedEventHandler wsAVCompleted;
        
        /// <remarks/>
        public event wsFDCompletedEventHandler wsFDCompleted;
        
        /// <remarks/>
        public event wsRTCompletedEventHandler wsRTCompleted;
        
        /// <remarks/>
        public event wsXePnrCompletedEventHandler wsXePnrCompleted;
        
        /// <remarks/>
        public event wsSSCompletedEventHandler wsSSCompleted;
        
        /// <remarks/>
        public event wsRT2CompletedEventHandler wsRT2Completed;
        
        /// <remarks/>
        public event wsFD2CompletedEventHandler wsFD2Completed;
        
        /// <remarks/>
        public event wsDSGCompletedEventHandler wsDSGCompleted;
        
        /// <remarks/>
        public event wsGetServerTimeCompletedEventHandler wsGetServerTimeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://hi.me.org/", ResponseNamespace="http://hi.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sayHi([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string s) {
            object[] results = this.Invoke("sayHi", new object[] {
                        s});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sayHiAsync(string s) {
            this.sayHiAsync(s, null);
        }
        
        /// <remarks/>
        public void sayHiAsync(string s, object userState) {
            if ((this.sayHiOperationCompleted == null)) {
                this.sayHiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsayHiOperationCompleted);
            }
            this.InvokeAsync("sayHi", new object[] {
                        s}, this.sayHiOperationCompleted, userState);
        }
        
        private void OnsayHiOperationCompleted(object arg) {
            if ((this.sayHiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sayHiCompleted(this, new sayHiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://hi.me.org/", ResponseNamespace="http://hi.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsAV([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string orgCity, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string dstCity, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string date, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string airline, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool direct, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool eticket) {
            object[] results = this.Invoke("wsAV", new object[] {
                        orgCity,
                        dstCity,
                        date,
                        airline,
                        direct,
                        eticket});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsAVAsync(string orgCity, string dstCity, string date, string airline, bool direct, bool eticket) {
            this.wsAVAsync(orgCity, dstCity, date, airline, direct, eticket, null);
        }
        
        /// <remarks/>
        public void wsAVAsync(string orgCity, string dstCity, string date, string airline, bool direct, bool eticket, object userState) {
            if ((this.wsAVOperationCompleted == null)) {
                this.wsAVOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsAVOperationCompleted);
            }
            this.InvokeAsync("wsAV", new object[] {
                        orgCity,
                        dstCity,
                        date,
                        airline,
                        direct,
                        eticket}, this.wsAVOperationCompleted, userState);
        }
        
        private void OnwsAVOperationCompleted(object arg) {
            if ((this.wsAVCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsAVCompleted(this, new wsAVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://hi.me.org/", ResponseNamespace="http://hi.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsFD([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string org, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string dst, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string date, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string airline, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string planeModel, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passType, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool fullFareBasis) {
            object[] results = this.Invoke("wsFD", new object[] {
                        org,
                        dst,
                        date,
                        airline,
                        planeModel,
                        passType,
                        fullFareBasis});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsFDAsync(string org, string dst, string date, string airline, string planeModel, string passType, bool fullFareBasis) {
            this.wsFDAsync(org, dst, date, airline, planeModel, passType, fullFareBasis, null);
        }
        
        /// <remarks/>
        public void wsFDAsync(string org, string dst, string date, string airline, string planeModel, string passType, bool fullFareBasis, object userState) {
            if ((this.wsFDOperationCompleted == null)) {
                this.wsFDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsFDOperationCompleted);
            }
            this.InvokeAsync("wsFD", new object[] {
                        org,
                        dst,
                        date,
                        airline,
                        planeModel,
                        passType,
                        fullFareBasis}, this.wsFDOperationCompleted, userState);
        }
        
        private void OnwsFDOperationCompleted(object arg) {
            if ((this.wsFDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsFDCompleted(this, new wsFDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://hi.me.org/", ResponseNamespace="http://hi.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsRT([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pnrno) {
            object[] results = this.Invoke("wsRT", new object[] {
                        pnrno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsRTAsync(string pnrno) {
            this.wsRTAsync(pnrno, null);
        }
        
        /// <remarks/>
        public void wsRTAsync(string pnrno, object userState) {
            if ((this.wsRTOperationCompleted == null)) {
                this.wsRTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsRTOperationCompleted);
            }
            this.InvokeAsync("wsRT", new object[] {
                        pnrno}, this.wsRTOperationCompleted, userState);
        }
        
        private void OnwsRTOperationCompleted(object arg) {
            if ((this.wsRTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsRTCompleted(this, new wsRTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://hi.me.org/", ResponseNamespace="http://hi.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsXePnr([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pnr, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string office) {
            object[] results = this.Invoke("wsXePnr", new object[] {
                        pnr,
                        office});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsXePnrAsync(string pnr, string office) {
            this.wsXePnrAsync(pnr, office, null);
        }
        
        /// <remarks/>
        public void wsXePnrAsync(string pnr, string office, object userState) {
            if ((this.wsXePnrOperationCompleted == null)) {
                this.wsXePnrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsXePnrOperationCompleted);
            }
            this.InvokeAsync("wsXePnr", new object[] {
                        pnr,
                        office}, this.wsXePnrOperationCompleted, userState);
        }
        
        private void OnwsXePnrOperationCompleted(object arg) {
            if ((this.wsXePnrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsXePnrCompleted(this, new wsXePnrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://hi.me.org/", ResponseNamespace="http://hi.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsSS([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string FlightNos, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ActionCodes, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string FlightDates, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string OrgCitys, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string DestCitys, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Bunks, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Names, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string LimitDate, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Cardids, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Remarks) {
            object[] results = this.Invoke("wsSS", new object[] {
                        FlightNos,
                        ActionCodes,
                        FlightDates,
                        OrgCitys,
                        DestCitys,
                        Bunks,
                        Names,
                        LimitDate,
                        Cardids,
                        Remarks});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsSSAsync(string FlightNos, string ActionCodes, string FlightDates, string OrgCitys, string DestCitys, string Bunks, string Names, string LimitDate, string Cardids, string Remarks) {
            this.wsSSAsync(FlightNos, ActionCodes, FlightDates, OrgCitys, DestCitys, Bunks, Names, LimitDate, Cardids, Remarks, null);
        }
        
        /// <remarks/>
        public void wsSSAsync(string FlightNos, string ActionCodes, string FlightDates, string OrgCitys, string DestCitys, string Bunks, string Names, string LimitDate, string Cardids, string Remarks, object userState) {
            if ((this.wsSSOperationCompleted == null)) {
                this.wsSSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsSSOperationCompleted);
            }
            this.InvokeAsync("wsSS", new object[] {
                        FlightNos,
                        ActionCodes,
                        FlightDates,
                        OrgCitys,
                        DestCitys,
                        Bunks,
                        Names,
                        LimitDate,
                        Cardids,
                        Remarks}, this.wsSSOperationCompleted, userState);
        }
        
        private void OnwsSSOperationCompleted(object arg) {
            if ((this.wsSSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsSSCompleted(this, new wsSSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://hi.me.org/", ResponseNamespace="http://hi.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsRT2([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pnr) {
            object[] results = this.Invoke("wsRT2", new object[] {
                        pnr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsRT2Async(string pnr) {
            this.wsRT2Async(pnr, null);
        }
        
        /// <remarks/>
        public void wsRT2Async(string pnr, object userState) {
            if ((this.wsRT2OperationCompleted == null)) {
                this.wsRT2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsRT2OperationCompleted);
            }
            this.InvokeAsync("wsRT2", new object[] {
                        pnr}, this.wsRT2OperationCompleted, userState);
        }
        
        private void OnwsRT2OperationCompleted(object arg) {
            if ((this.wsRT2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsRT2Completed(this, new wsRT2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://hi.me.org/", ResponseNamespace="http://hi.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsFD2([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string org, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string dst, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string date, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string airline, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string planeModel, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passType, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool fullFareBasis) {
            object[] results = this.Invoke("wsFD2", new object[] {
                        org,
                        dst,
                        date,
                        airline,
                        planeModel,
                        passType,
                        fullFareBasis});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsFD2Async(string org, string dst, string date, string airline, string planeModel, string passType, bool fullFareBasis) {
            this.wsFD2Async(org, dst, date, airline, planeModel, passType, fullFareBasis, null);
        }
        
        /// <remarks/>
        public void wsFD2Async(string org, string dst, string date, string airline, string planeModel, string passType, bool fullFareBasis, object userState) {
            if ((this.wsFD2OperationCompleted == null)) {
                this.wsFD2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsFD2OperationCompleted);
            }
            this.InvokeAsync("wsFD2", new object[] {
                        org,
                        dst,
                        date,
                        airline,
                        planeModel,
                        passType,
                        fullFareBasis}, this.wsFD2OperationCompleted, userState);
        }
        
        private void OnwsFD2OperationCompleted(object arg) {
            if ((this.wsFD2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsFD2Completed(this, new wsFD2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://hi.me.org/", ResponseNamespace="http://hi.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsDSG([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pnr) {
            object[] results = this.Invoke("wsDSG", new object[] {
                        pnr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsDSGAsync(string pnr) {
            this.wsDSGAsync(pnr, null);
        }
        
        /// <remarks/>
        public void wsDSGAsync(string pnr, object userState) {
            if ((this.wsDSGOperationCompleted == null)) {
                this.wsDSGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsDSGOperationCompleted);
            }
            this.InvokeAsync("wsDSG", new object[] {
                        pnr}, this.wsDSGOperationCompleted, userState);
        }
        
        private void OnwsDSGOperationCompleted(object arg) {
            if ((this.wsDSGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsDSGCompleted(this, new wsDSGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://hi.me.org/", ResponseNamespace="http://hi.me.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsGetServerTime() {
            object[] results = this.Invoke("wsGetServerTime", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsGetServerTimeAsync() {
            this.wsGetServerTimeAsync(null);
        }
        
        /// <remarks/>
        public void wsGetServerTimeAsync(object userState) {
            if ((this.wsGetServerTimeOperationCompleted == null)) {
                this.wsGetServerTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsGetServerTimeOperationCompleted);
            }
            this.InvokeAsync("wsGetServerTime", new object[0], this.wsGetServerTimeOperationCompleted, userState);
        }
        
        private void OnwsGetServerTimeOperationCompleted(object arg) {
            if ((this.wsGetServerTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsGetServerTimeCompleted(this, new wsGetServerTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void sayHiCompletedEventHandler(object sender, sayHiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sayHiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sayHiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void wsAVCompletedEventHandler(object sender, wsAVCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsAVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsAVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void wsFDCompletedEventHandler(object sender, wsFDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsFDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsFDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void wsRTCompletedEventHandler(object sender, wsRTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsRTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsRTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void wsXePnrCompletedEventHandler(object sender, wsXePnrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsXePnrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsXePnrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void wsSSCompletedEventHandler(object sender, wsSSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsSSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsSSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void wsRT2CompletedEventHandler(object sender, wsRT2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsRT2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsRT2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void wsFD2CompletedEventHandler(object sender, wsFD2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsFD2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsFD2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void wsDSGCompletedEventHandler(object sender, wsDSGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsDSGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsDSGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void wsGetServerTimeCompletedEventHandler(object sender, wsGetServerTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsGetServerTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsGetServerTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591