//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace ChinaLife_BJ
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "TransportAccidentForSaveServerSoap11Binding", Namespace = "http://domain.webservice.prpall.sinosoft.com")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TXInsuranceExtension))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TXInsurance))]
    public partial class TransportAccidentForSaveServer : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback savePolicyOperationCompleted;

        static string[] config = System.Configuration.ConfigurationManager.AppSettings["ChinaLife_BJ_Issuing"].Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries);

        /// <remarks/>
        public TransportAccidentForSaveServer()
        {
            this.Url = config[0];
        }

        /// <remarks/>
        public event savePolicyCompletedEventHandler savePolicyCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:savePolicy", RequestNamespace = "http://domain.webservice.prpall.sinosoft.com", ResponseNamespace = "http://domain.webservice.prpall.sinosoft.com", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable = true)]
        public TransportAccidentResponseDto savePolicy([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string passWord, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] TransportAccidentForSaveRequsetDto transportAccidentForSaveRequsetDto)
        {
            object[] results = this.Invoke("savePolicy", new object[] {
                        userName,
                        passWord,
                        transportAccidentForSaveRequsetDto});
            return ((TransportAccidentResponseDto)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginsavePolicy(string userName, string passWord, TransportAccidentForSaveRequsetDto transportAccidentForSaveRequsetDto, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("savePolicy", new object[] {
                        userName,
                        passWord,
                        transportAccidentForSaveRequsetDto}, callback, asyncState);
        }

        /// <remarks/>
        public TransportAccidentResponseDto EndsavePolicy(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((TransportAccidentResponseDto)(results[0]));
        }

        /// <remarks/>
        public void savePolicyAsync(string userName, string passWord, TransportAccidentForSaveRequsetDto transportAccidentForSaveRequsetDto)
        {
            this.savePolicyAsync(userName, passWord, transportAccidentForSaveRequsetDto, null);
        }

        /// <remarks/>
        public void savePolicyAsync(string userName, string passWord, TransportAccidentForSaveRequsetDto transportAccidentForSaveRequsetDto, object userState)
        {
            if ((this.savePolicyOperationCompleted == null))
            {
                this.savePolicyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsavePolicyOperationCompleted);
            }
            this.InvokeAsync("savePolicy", new object[] {
                        userName,
                        passWord,
                        transportAccidentForSaveRequsetDto}, this.savePolicyOperationCompleted, userState);
        }

        private void OnsavePolicyOperationCompleted(object arg)
        {
            if ((this.savePolicyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.savePolicyCompleted(this, new savePolicyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://dto.webservice.prpall.sinosoft.com/xsd")]
    public partial class TransportAccidentForSaveRequsetDto
    {

        private string agencyNoField;

        private string birthDateField;

        private string customerFlightNoField;

        private string customerPhoneField;

        private string effDateField;

        private string functionIdField;

        private string genderField;

        private string idNoField;

        private string idTypeField;

        private string matuDateField;

        private string nameField;

        private string orderCodeField;

        private string passwordField;

        private string productNoField;

        private TXInsuranceRequest tXInsuranceRequestField;

        private TXInsuranceRequestExtension tXInsuranceRequestExtensionField;

        private string unitsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string agencyNo
        {
            get
            {
                return this.agencyNoField;
            }
            set
            {
                this.agencyNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string birthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string customerFlightNo
        {
            get
            {
                return this.customerFlightNoField;
            }
            set
            {
                this.customerFlightNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string customerPhone
        {
            get
            {
                return this.customerPhoneField;
            }
            set
            {
                this.customerPhoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string effDate
        {
            get
            {
                return this.effDateField;
            }
            set
            {
                this.effDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string functionId
        {
            get
            {
                return this.functionIdField;
            }
            set
            {
                this.functionIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string idNo
        {
            get
            {
                return this.idNoField;
            }
            set
            {
                this.idNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string idType
        {
            get
            {
                return this.idTypeField;
            }
            set
            {
                this.idTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string matuDate
        {
            get
            {
                return this.matuDateField;
            }
            set
            {
                this.matuDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string orderCode
        {
            get
            {
                return this.orderCodeField;
            }
            set
            {
                this.orderCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string productNo
        {
            get
            {
                return this.productNoField;
            }
            set
            {
                this.productNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public TXInsuranceRequest tXInsuranceRequest
        {
            get
            {
                return this.tXInsuranceRequestField;
            }
            set
            {
                this.tXInsuranceRequestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public TXInsuranceRequestExtension tXInsuranceRequestExtension
        {
            get
            {
                return this.tXInsuranceRequestExtensionField;
            }
            set
            {
                this.tXInsuranceRequestExtensionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void savePolicyCompletedEventHandler(object sender, savePolicyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class savePolicyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal savePolicyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public TransportAccidentResponseDto Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((TransportAccidentResponseDto)(this.results[0]));
            }
        }
    }
}
