//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.1。
// 
namespace Huayubaoxian
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback confirmpolicyOperationCompleted;
        
        private System.Threading.SendOrPostCallback quitpolicyOperationCompleted;
        
        private System.Threading.SendOrPostCallback getpolicyOperationCompleted;
        
        private System.Threading.SendOrPostCallback getpolicynumOperationCompleted;
        
        /// <remarks/>
        public Service() {
            this.Url = "http://test.huayubaoxian.net/Service.asmx";
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event confirmpolicyCompletedEventHandler confirmpolicyCompleted;
        
        /// <remarks/>
        public event quitpolicyCompletedEventHandler quitpolicyCompleted;
        
        /// <remarks/>
        public event getpolicyCompletedEventHandler getpolicyCompleted;
        
        /// <remarks/>
        public event getpolicynumCompletedEventHandler getpolicynumCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/confirmpolicy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string confirmpolicy(policy obj) {
            object[] results = this.Invoke("confirmpolicy", new object[] {
                        obj});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginconfirmpolicy(policy obj, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("confirmpolicy", new object[] {
                        obj}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endconfirmpolicy(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void confirmpolicyAsync(policy obj) {
            this.confirmpolicyAsync(obj, null);
        }
        
        /// <remarks/>
        public void confirmpolicyAsync(policy obj, object userState) {
            if ((this.confirmpolicyOperationCompleted == null)) {
                this.confirmpolicyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfirmpolicyOperationCompleted);
            }
            this.InvokeAsync("confirmpolicy", new object[] {
                        obj}, this.confirmpolicyOperationCompleted, userState);
        }
        
        private void OnconfirmpolicyOperationCompleted(object arg) {
            if ((this.confirmpolicyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.confirmpolicyCompleted(this, new confirmpolicyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/quitpolicy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string quitpolicy(string username, string password, string id) {
            object[] results = this.Invoke("quitpolicy", new object[] {
                        username,
                        password,
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginquitpolicy(string username, string password, string id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("quitpolicy", new object[] {
                        username,
                        password,
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endquitpolicy(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void quitpolicyAsync(string username, string password, string id) {
            this.quitpolicyAsync(username, password, id, null);
        }
        
        /// <remarks/>
        public void quitpolicyAsync(string username, string password, string id, object userState) {
            if ((this.quitpolicyOperationCompleted == null)) {
                this.quitpolicyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnquitpolicyOperationCompleted);
            }
            this.InvokeAsync("quitpolicy", new object[] {
                        username,
                        password,
                        id}, this.quitpolicyOperationCompleted, userState);
        }
        
        private void OnquitpolicyOperationCompleted(object arg) {
            if ((this.quitpolicyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.quitpolicyCompleted(this, new quitpolicyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getpolicy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getpolicy(string username, string password, string id) {
            object[] results = this.Invoke("getpolicy", new object[] {
                        username,
                        password,
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begingetpolicy(string username, string password, string id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getpolicy", new object[] {
                        username,
                        password,
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endgetpolicy(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getpolicyAsync(string username, string password, string id) {
            this.getpolicyAsync(username, password, id, null);
        }
        
        /// <remarks/>
        public void getpolicyAsync(string username, string password, string id, object userState) {
            if ((this.getpolicyOperationCompleted == null)) {
                this.getpolicyOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetpolicyOperationCompleted);
            }
            this.InvokeAsync("getpolicy", new object[] {
                        username,
                        password,
                        id}, this.getpolicyOperationCompleted, userState);
        }
        
        private void OngetpolicyOperationCompleted(object arg) {
            if ((this.getpolicyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getpolicyCompleted(this, new getpolicyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getpolicynum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getpolicynum(string username, string password) {
            object[] results = this.Invoke("getpolicynum", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begingetpolicynum(string username, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getpolicynum", new object[] {
                        username,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endgetpolicynum(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getpolicynumAsync(string username, string password) {
            this.getpolicynumAsync(username, password, null);
        }
        
        /// <remarks/>
        public void getpolicynumAsync(string username, string password, object userState) {
            if ((this.getpolicynumOperationCompleted == null)) {
                this.getpolicynumOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetpolicynumOperationCompleted);
            }
            this.InvokeAsync("getpolicynum", new object[] {
                        username,
                        password}, this.getpolicynumOperationCompleted, userState);
        }
        
        private void OngetpolicynumOperationCompleted(object arg) {
            if ((this.getpolicynumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getpolicynumCompleted(this, new getpolicynumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class policy {
        
        private string useridField;
        
        private string passwordField;
        
        private string planNoField;
        
        private string oPER_DATEField;
        
        private string begdateField;
        
        private string app_nameField;
        
        private string iDTypeField;
        
        private string app_idField;
        
        private string app_addressField;
        
        private string app_zipField;
        
        private string app_emailField;
        
        private string app_teleField;
        
        private string app_cellnoField;
        
        private string goflightNoField;
        
        private string remarkField;
        
        /// <remarks/>
        public string userid {
            get {
                return this.useridField;
            }
            set {
                this.useridField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string PlanNo {
            get {
                return this.planNoField;
            }
            set {
                this.planNoField = value;
            }
        }
        
        /// <remarks/>
        public string OPER_DATE {
            get {
                return this.oPER_DATEField;
            }
            set {
                this.oPER_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string begdate {
            get {
                return this.begdateField;
            }
            set {
                this.begdateField = value;
            }
        }
        
        /// <remarks/>
        public string App_name {
            get {
                return this.app_nameField;
            }
            set {
                this.app_nameField = value;
            }
        }
        
        /// <remarks/>
        public string IDType {
            get {
                return this.iDTypeField;
            }
            set {
                this.iDTypeField = value;
            }
        }
        
        /// <remarks/>
        public string App_id {
            get {
                return this.app_idField;
            }
            set {
                this.app_idField = value;
            }
        }
        
        /// <remarks/>
        public string App_address {
            get {
                return this.app_addressField;
            }
            set {
                this.app_addressField = value;
            }
        }
        
        /// <remarks/>
        public string App_zip {
            get {
                return this.app_zipField;
            }
            set {
                this.app_zipField = value;
            }
        }
        
        /// <remarks/>
        public string App_email {
            get {
                return this.app_emailField;
            }
            set {
                this.app_emailField = value;
            }
        }
        
        /// <remarks/>
        public string App_tele {
            get {
                return this.app_teleField;
            }
            set {
                this.app_teleField = value;
            }
        }
        
        /// <remarks/>
        public string App_cellno {
            get {
                return this.app_cellnoField;
            }
            set {
                this.app_cellnoField = value;
            }
        }
        
        /// <remarks/>
        public string GoflightNo {
            get {
                return this.goflightNoField;
            }
            set {
                this.goflightNoField = value;
            }
        }
        
        /// <remarks/>
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void confirmpolicyCompletedEventHandler(object sender, confirmpolicyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class confirmpolicyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal confirmpolicyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void quitpolicyCompletedEventHandler(object sender, quitpolicyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class quitpolicyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal quitpolicyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getpolicyCompletedEventHandler(object sender, getpolicyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getpolicyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getpolicyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void getpolicynumCompletedEventHandler(object sender, getpolicynumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getpolicynumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getpolicynumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
