//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1882
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Jiandanbao
{
    using System;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;

    // 
    // 此源代码由 wsdl 自动生成, Version=2.0.50727.42。
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "iOrderWebServiceSoap", Namespace = "http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityBaseCore))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JdbOrder2Article[]))]
    public partial class iOrderWebService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;

        private System.Threading.SendOrPostCallback GetOrderInfoOperationCompleted;

        private System.Threading.SendOrPostCallback SendOrderOperationCompleted;

        private System.Threading.SendOrPostCallback CancelOrderOperationCompleted;

        private System.Threading.SendOrPostCallback GetOrderOperationCompleted;

        private System.Threading.SendOrPostCallback UpdateOrderStatusOperationCompleted;

        private System.Threading.SendOrPostCallback VerifyOrderInfoOperationCompleted;

        /// <remarks/>
        public iOrderWebService()
        {
            this.Url = "http://api.jiandanbao.com/iOrderWebService.asmx";
        }

        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;

        /// <remarks/>
        public event GetOrderInfoCompletedEventHandler GetOrderInfoCompleted;

        /// <remarks/>
        public event SendOrderCompletedEventHandler SendOrderCompleted;

        /// <remarks/>
        public event CancelOrderCompletedEventHandler CancelOrderCompleted;

        /// <remarks/>
        public event GetOrderCompletedEventHandler GetOrderCompleted;

        /// <remarks/>
        public event UpdateOrderStatusCompletedEventHandler UpdateOrderStatusCompleted;

        /// <remarks/>
        public event VerifyOrderInfoCompletedEventHandler VerifyOrderInfoCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld()
        {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void HelloWorldAsync()
        {
            this.HelloWorldAsync(null);
        }

        /// <remarks/>
        public void HelloWorldAsync(object userState)
        {
            if ((this.HelloWorldOperationCompleted == null))
            {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }

        private void OnHelloWorldOperationCompleted(object arg)
        {
            if ((this.HelloWorldCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderInfo", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderInfo GetOrderInfo(string OrrID)
        {
            object[] results = this.Invoke("GetOrderInfo", new object[] {
                    OrrID});
            return ((OrderInfo)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetOrderInfo(string OrrID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetOrderInfo", new object[] {
                    OrrID}, callback, asyncState);
        }

        /// <remarks/>
        public OrderInfo EndGetOrderInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((OrderInfo)(results[0]));
        }

        /// <remarks/>
        public void GetOrderInfoAsync(string OrrID)
        {
            this.GetOrderInfoAsync(OrrID, null);
        }

        /// <remarks/>
        public void GetOrderInfoAsync(string OrrID, object userState)
        {
            if ((this.GetOrderInfoOperationCompleted == null))
            {
                this.GetOrderInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderInfoOperationCompleted);
            }
            this.InvokeAsync("GetOrderInfo", new object[] {
                    OrrID}, this.GetOrderInfoOperationCompleted, userState);
        }

        private void OnGetOrderInfoOperationCompleted(object arg)
        {
            if ((this.GetOrderInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderInfoCompleted(this, new GetOrderInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendOrder", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendOrder(string xmlDoc)
        {
            object[] results = this.Invoke("SendOrder", new object[] {
                    xmlDoc});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSendOrder(string xmlDoc, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SendOrder", new object[] {
                    xmlDoc}, callback, asyncState);
        }

        /// <remarks/>
        public string EndSendOrder(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void SendOrderAsync(string xmlDoc)
        {
            this.SendOrderAsync(xmlDoc, null);
        }

        /// <remarks/>
        public void SendOrderAsync(string xmlDoc, object userState)
        {
            if ((this.SendOrderOperationCompleted == null))
            {
                this.SendOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOrderOperationCompleted);
            }
            this.InvokeAsync("SendOrder", new object[] {
                    xmlDoc}, this.SendOrderOperationCompleted, userState);
        }

        private void OnSendOrderOperationCompleted(object arg)
        {
            if ((this.SendOrderCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendOrderCompleted(this, new SendOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelOrder", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CancelOrder(string XmlDoc)
        {
            object[] results = this.Invoke("CancelOrder", new object[] {
                    XmlDoc});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCancelOrder(string XmlDoc, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CancelOrder", new object[] {
                    XmlDoc}, callback, asyncState);
        }

        /// <remarks/>
        public string EndCancelOrder(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CancelOrderAsync(string XmlDoc)
        {
            this.CancelOrderAsync(XmlDoc, null);
        }

        /// <remarks/>
        public void CancelOrderAsync(string XmlDoc, object userState)
        {
            if ((this.CancelOrderOperationCompleted == null))
            {
                this.CancelOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelOrderOperationCompleted);
            }
            this.InvokeAsync("CancelOrder", new object[] {
                    XmlDoc}, this.CancelOrderOperationCompleted, userState);
        }

        private void OnCancelOrderOperationCompleted(object arg)
        {
            if ((this.CancelOrderCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelOrderCompleted(this, new CancelOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrder", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetOrder(string XmlDoc)
        {
            object[] results = this.Invoke("GetOrder", new object[] {
                    XmlDoc});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetOrder(string XmlDoc, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetOrder", new object[] {
                    XmlDoc}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetOrder(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetOrderAsync(string XmlDoc)
        {
            this.GetOrderAsync(XmlDoc, null);
        }

        /// <remarks/>
        public void GetOrderAsync(string XmlDoc, object userState)
        {
            if ((this.GetOrderOperationCompleted == null))
            {
                this.GetOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderOperationCompleted);
            }
            this.InvokeAsync("GetOrder", new object[] {
                    XmlDoc}, this.GetOrderOperationCompleted, userState);
        }

        private void OnGetOrderOperationCompleted(object arg)
        {
            if ((this.GetOrderCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderCompleted(this, new GetOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOrderStatus", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateOrderStatus(string OrrID, string Status, string PDFUrl, string XMLUrl, string PolicyNum, string VerifyDate)
        {
            object[] results = this.Invoke("UpdateOrderStatus", new object[] {
                    OrrID,
                    Status,
                    PDFUrl,
                    XMLUrl,
                    PolicyNum,
                    VerifyDate});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginUpdateOrderStatus(string OrrID, string Status, string PDFUrl, string XMLUrl, string PolicyNum, string VerifyDate, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UpdateOrderStatus", new object[] {
                    OrrID,
                    Status,
                    PDFUrl,
                    XMLUrl,
                    PolicyNum,
                    VerifyDate}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndUpdateOrderStatus(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void UpdateOrderStatusAsync(string OrrID, string Status, string PDFUrl, string XMLUrl, string PolicyNum, string VerifyDate)
        {
            this.UpdateOrderStatusAsync(OrrID, Status, PDFUrl, XMLUrl, PolicyNum, VerifyDate, null);
        }

        /// <remarks/>
        public void UpdateOrderStatusAsync(string OrrID, string Status, string PDFUrl, string XMLUrl, string PolicyNum, string VerifyDate, object userState)
        {
            if ((this.UpdateOrderStatusOperationCompleted == null))
            {
                this.UpdateOrderStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrderStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateOrderStatus", new object[] {
                    OrrID,
                    Status,
                    PDFUrl,
                    XMLUrl,
                    PolicyNum,
                    VerifyDate}, this.UpdateOrderStatusOperationCompleted, userState);
        }

        private void OnUpdateOrderStatusOperationCompleted(object arg)
        {
            if ((this.UpdateOrderStatusCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrderStatusCompleted(this, new UpdateOrderStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerifyOrderInfo", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerifyOrderInfo(string xmlDoc)
        {
            object[] results = this.Invoke("VerifyOrderInfo", new object[] {
                    xmlDoc});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginVerifyOrderInfo(string xmlDoc, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("VerifyOrderInfo", new object[] {
                    xmlDoc}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndVerifyOrderInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void VerifyOrderInfoAsync(string xmlDoc)
        {
            this.VerifyOrderInfoAsync(xmlDoc, null);
        }

        /// <remarks/>
        public void VerifyOrderInfoAsync(string xmlDoc, object userState)
        {
            if ((this.VerifyOrderInfoOperationCompleted == null))
            {
                this.VerifyOrderInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyOrderInfoOperationCompleted);
            }
            this.InvokeAsync("VerifyOrderInfo", new object[] {
                    xmlDoc}, this.VerifyOrderInfoOperationCompleted, userState);
        }

        private void OnVerifyOrderInfoOperationCompleted(object arg)
        {
            if ((this.VerifyOrderInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyOrderInfoCompleted(this, new VerifyOrderInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class OrderInfo
    {

        private JdbOrder2Article[] argumentField;

        private JdbOrder2Person[] userField;

        private JdbOrder orderField;

        /// <remarks/>
        public JdbOrder2Article[] Argument
        {
            get
            {
                return this.argumentField;
            }
            set
            {
                this.argumentField = value;
            }
        }

        /// <remarks/>
        public JdbOrder2Person[] User
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        public JdbOrder Order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class JdbOrder2Article : JdbOrder2ArticleBase
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JdbOrder2Article))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public abstract partial class JdbOrder2ArticleBase : EntityBase
    {

        private string oreIdField;

        private string originalOreIdField;

        private string orrIdField;

        private string areIdField;

        private string argumentListField;

        private System.Nullable<decimal> amountField;

        private string infoMirrorField;

        /// <remarks/>
        public string OreId
        {
            get
            {
                return this.oreIdField;
            }
            set
            {
                this.oreIdField = value;
            }
        }

        /// <remarks/>
        public string OriginalOreId
        {
            get
            {
                return this.originalOreIdField;
            }
            set
            {
                this.originalOreIdField = value;
            }
        }

        /// <remarks/>
        public string OrrId
        {
            get
            {
                return this.orrIdField;
            }
            set
            {
                this.orrIdField = value;
            }
        }

        /// <remarks/>
        public string AreId
        {
            get
            {
                return this.areIdField;
            }
            set
            {
                this.areIdField = value;
            }
        }

        /// <remarks/>
        public string ArgumentList
        {
            get
            {
                return this.argumentListField;
            }
            set
            {
                this.argumentListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        public string InfoMirror
        {
            get
            {
                return this.infoMirrorField;
            }
            set
            {
                this.infoMirrorField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JdbOrder2PersonBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JdbOrder2Person))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JdbOrderBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JdbOrder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JdbOrder2ArticleBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JdbOrder2Article))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public abstract partial class EntityBase : EntityBaseCore
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JdbOrder2PersonBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JdbOrder2Person))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JdbOrderBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JdbOrder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JdbOrder2ArticleBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JdbOrder2Article))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public abstract partial class EntityBaseCore
    {

        private object tagField;

        /// <remarks/>
        public object Tag
        {
            get
            {
                return this.tagField;
            }
            set
            {
                this.tagField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JdbOrder2Person))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public abstract partial class JdbOrder2PersonBase : EntityBase
    {

        private string ornIdField;

        private string originalOrnIdField;

        private string orrIdField;

        private System.Nullable<int> relationshipField;

        private string personIdField;

        private System.Nullable<int> ordersField;

        private string infoMirrorField;

        /// <remarks/>
        public string OrnId
        {
            get
            {
                return this.ornIdField;
            }
            set
            {
                this.ornIdField = value;
            }
        }

        /// <remarks/>
        public string OriginalOrnId
        {
            get
            {
                return this.originalOrnIdField;
            }
            set
            {
                this.originalOrnIdField = value;
            }
        }

        /// <remarks/>
        public string OrrId
        {
            get
            {
                return this.orrIdField;
            }
            set
            {
                this.orrIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> Relationship
        {
            get
            {
                return this.relationshipField;
            }
            set
            {
                this.relationshipField = value;
            }
        }

        /// <remarks/>
        public string PersonId
        {
            get
            {
                return this.personIdField;
            }
            set
            {
                this.personIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> Orders
        {
            get
            {
                return this.ordersField;
            }
            set
            {
                this.ordersField = value;
            }
        }

        /// <remarks/>
        public string InfoMirror
        {
            get
            {
                return this.infoMirrorField;
            }
            set
            {
                this.infoMirrorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class JdbOrder2Person : JdbOrder2PersonBase
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JdbOrder))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public abstract partial class JdbOrderBase : EntityBase
    {

        private string orrIdField;

        private string originalOrrIdField;

        private string ordNumField;

        private string usrIdField;

        private System.Nullable<System.DateTime> createDateField;

        private System.Nullable<int> statusField;

        private System.Nullable<decimal> amountField;

        private System.Nullable<decimal> opriceField;

        private System.Nullable<decimal> pointsField;

        private string payWayField;

        private string resultUrlField;

        private string notifyUrlField;

        private string xmlUrlField;

        private string pdfUrlField;

        private string ext1Field;

        private string ext2Field;

        /// <remarks/>
        public string OrrId
        {
            get
            {
                return this.orrIdField;
            }
            set
            {
                this.orrIdField = value;
            }
        }

        /// <remarks/>
        public string OriginalOrrId
        {
            get
            {
                return this.originalOrrIdField;
            }
            set
            {
                this.originalOrrIdField = value;
            }
        }

        /// <remarks/>
        public string OrdNum
        {
            get
            {
                return this.ordNumField;
            }
            set
            {
                this.ordNumField = value;
            }
        }

        /// <remarks/>
        public string UsrId
        {
            get
            {
                return this.usrIdField;
            }
            set
            {
                this.usrIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> CreateDate
        {
            get
            {
                return this.createDateField;
            }
            set
            {
                this.createDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> Oprice
        {
            get
            {
                return this.opriceField;
            }
            set
            {
                this.opriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> Points
        {
            get
            {
                return this.pointsField;
            }
            set
            {
                this.pointsField = value;
            }
        }

        /// <remarks/>
        public string PayWay
        {
            get
            {
                return this.payWayField;
            }
            set
            {
                this.payWayField = value;
            }
        }

        /// <remarks/>
        public string ResultUrl
        {
            get
            {
                return this.resultUrlField;
            }
            set
            {
                this.resultUrlField = value;
            }
        }

        /// <remarks/>
        public string NotifyUrl
        {
            get
            {
                return this.notifyUrlField;
            }
            set
            {
                this.notifyUrlField = value;
            }
        }

        /// <remarks/>
        public string XmlUrl
        {
            get
            {
                return this.xmlUrlField;
            }
            set
            {
                this.xmlUrlField = value;
            }
        }

        /// <remarks/>
        public string PdfUrl
        {
            get
            {
                return this.pdfUrlField;
            }
            set
            {
                this.pdfUrlField = value;
            }
        }

        /// <remarks/>
        public string Ext1
        {
            get
            {
                return this.ext1Field;
            }
            set
            {
                this.ext1Field = value;
            }
        }

        /// <remarks/>
        public string Ext2
        {
            get
            {
                return this.ext2Field;
            }
            set
            {
                this.ext2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class JdbOrder : JdbOrderBase
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetOrderInfoCompletedEventHandler(object sender, GetOrderInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetOrderInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public OrderInfo Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OrderInfo)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void SendOrderCompletedEventHandler(object sender, SendOrderCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SendOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void CancelOrderCompletedEventHandler(object sender, CancelOrderCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CancelOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetOrderCompletedEventHandler(object sender, GetOrderCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void UpdateOrderStatusCompletedEventHandler(object sender, UpdateOrderStatusCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOrderStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal UpdateOrderStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void VerifyOrderInfoCompletedEventHandler(object sender, VerifyOrderInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyOrderInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VerifyOrderInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}